fail_fast: true

repos:
  # Checking if large files are present (max size: 1Mb)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1000
          - --enforce-all

  # Sorting imports (isort)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--config-file", "setup.cfg"]

  # Format docstrings to respect PEP 257
  - repo: https://github.com/myint/docformatter
    rev: v1.7.3
    hooks:
      - id: docformatter

  # Checking code compliance to pep8 (Flake 8, McCabe)
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--config-file", "setup.cfg"]

# Performs type checking and missing type annotations on code
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        language: system
        args: ["--config-file", "setup.cfg"]