fail_fast: true

repos:
  # Checking if large files are present (max size: 1Mb)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1000
          - --enforce-all

  # Sorting imports (isort)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort