services:
  postgres:
    image: postgres:13.4
    container_name: postgres
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chat_room
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    # Persist postgres volume so docker-compose down doesn't delete it
    volumes:
      - db-data:/var/lib/postgresql/data
    # Expose postgres port on 5431 to enable local debugging
    ports:
      - "5431:5432"

  fastapi:
    env_file:
      - ./config/server.env
    build: .
    restart: always
    environment:
      DB_URI: "postgresql://postgres:postgres@postgres/chat_room"
      APP_NAME: "backend"
    networks:
      - default
    volumes:
      - ./application:/app/application
      - ./alembic:/app/alembic
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-9000}:${SERVER_PORT:-9000}"


volumes:
  db-data:
    driver: local
