"""Added messages table

Revision ID: 6d1b6bb4feb8
Revises: 4c3d9c86b91d
Create Date: 2024-07-21 19:29:45.602596

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6d1b6bb4feb8'
down_revision = '4c3d9c86b91d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
